version: '3.8'
services:
  mysql:
    image: mysql:8.0.29
    container_name: mysql-8.0.29
    build:
      context: ./mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql/conf-21:/etc/mysql/conf.d
      - ./mysql/logs-21:/logs
      - ./mysql/data-21:/var/lib/mysql
    command: [
        'mysqld',
        '--innodb-buffer-pool-size=80M',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_general_ci',
        '--default-time-zone=+8:00',
        '--lower-case-table-names=1'
    ]
    environment:
      MYSQL_DATABASE: 'pf-config'
      MYSQL_ROOT_PASSWORD: 123456