version: '3.8'
services:
  nacos:
    image: nacos/nacos-server:v2.1.0
    container_name: nacos-2.1.0
    build:
      context: ./nacos
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    restart: on-failure
    volumes:
      - ./nacos/logs:/home/nacos/logs
    environment:
      PREFER_HOST_MODE: hostname #如果支持主机名可以使用hostname,否则使用ip，默认也是ip
      SPRING_DATASOURCE_PLATFORM: mysql #数据源平台 仅支持mysql或不保存empty
      MODE: standalone
      MYSQL_SERVICE_HOST: 192.168.1.11
      MYSQL_SERVICE_DB_NAME: pf-config
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: 123456
      NACOS_APPLICATION_PORT: 8848
      JVM_XMS: 512m
      JVM_MMS: 320m